name: Xcode - Build and Analyze

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and analyze Word Snip
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and analyze
        run: |
          xcodebuild \
            -project WordSnip.xcodeproj \
            -scheme WordSnip \
            -configuration Release \
            -destination 'generic/platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            clean build analyze
